### ISSUE TITLE
Logic nghiệp vụ

### ISSUE THREAD

**Issue by nghiatm341** [MasterPi-2124/CNWeb30-Backend#12]
Các logic nghiệp vụ sẽ được bàn ở đây, front cần gì back sẽ xử lý

**Comment by masterpi007** [comment]
ui add xong ms de y issue nay :))

**Comment by masterpi007** [comment]
To-do list:
 - [x] #18 
 - [x] Add get all classes by semester. Return a list of semester, each semester object contain list of class ID
 - [x] quiz records should be a list of quizzes object, each object has a param "records", is a list of records, not each records as right now, so when a person are submitting, it will update records param of that quiz object by pushing the new record to the list, or updating if the record was in the list

**Comment by masterpi007** [comment]
thanks a lot, took me 1 hrs to figure out the backend code is updated :))

**Comment by nghiatm341** [comment]
- [x] #25

**Comment by nghiatm341** [comment]
https://github.com/MasterPi-2124/CNWeb30-Backend/tree/refractor/quizRecord
