### ISSUE TITLE
new params to quizzes

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#14]
each quiz should also have these params:
 - status: Incoming, happening, and finished. the status can be achieved by comparing startTime, endTime and current time
 - QR raw image URL. QR logic should be executed right from back end
proposed changes:
 - change classID type from `string` to `int`
 - if possible, change ID to normal number, starting from 1, not random string
 - `__v` is unused

**Comment by nghiatm341** [comment]
- classID để dành cho lưu cái id được tạo ra để liên kết, tìm kiếm, không phải mã lớp, cái name mới chứa mã lớp (hoặc mình có thể thệm trường riêng cho nó)
- Status, ok để mình xem
- __v là mặc định có, mongoose khuyên là không nên bỏ, trừ khi mình biết mình đang làm gì (mình có thể ẩn nó đi để front không nhận nó nữa)

**Comment by nghiatm341** [comment]
> each quiz should also have these params:
> 
> * status: Incoming, happening, and finished. the status can be achieved by comparing startTime, endTime and current time
> * QR raw image URL. QR logic should be executed right from back end
>   proposed changes:
> * change classID type from `string` to `int`
> * if possible, change ID to normal number, starting from 1, not random string
> * `__v` is unused

@MasterPi-2124 
- classID để dành cho lưu cái id được tạo ra để liên kết, tìm kiếm, không phải mã lớp, cái name mới chứa mã lớp (hoặc mình có thể thệm trường riêng cho nó)
- Status, ok để mình xem
- __v là mặc định có, mongoose khuyên là không nên bỏ, trừ khi mình biết mình đang làm gì (mình có thể ẩn nó đi để front không nhận nó nữa)
- Mình chưa hiểu ý bạn về phần QR, bạn giải thích rõ hơn được không?

**Comment by masterpi007** [comment]
- ô cứ tưởng classId là mã lớp :))) Nếu vậy mình nghĩ nên đổi lại tên param cho đỡ nhầm lẫn, classID sẽ là mã lớp của quiz, còn ID có thẻ là id bạn đang define cũng đc
- sau khi 1 quiz đc tạo trên backend, 1 link đến quiz sẽ đc tự động gen ra để sv truy cập vào, và 1 mã QR của URL sẽ đc gen ra và để trong api.

**Comment by nghiatm341** [comment]
> * ô cứ tưởng classId là mã lớp :))) Nếu vậy mình nghĩ nên đổi lại tên param cho đỡ nhầm lẫn, classID sẽ là mã lớp của quiz, còn ID có thẻ là id bạn đang define cũng đc
- OK, thực ra quiz là cái mình tạo ra đầu tiên, nó còn nhiều vấn đề nên mình định tranh thủ lần này để sửa lại nhiều thứ

> * sau khi 1 quiz đc tạo trên backend, 1 link đến quiz sẽ đc tự động gen ra để sv truy cập vào, và 1 mã QR của URL sẽ đc gen ra và để trong api.
- Thực ra các link / QR để sinh viên truy cập vào nên dẫn tới một trang của front để sinh viên điền thông tin điểm danh vào, khi sinh viên nhấn OK thì front sẽ gọi api tạo quizRecord để lưu thông tin sinh viên điền (lưu lượt điểm danh) rồi chuyển tiếp sinh viên đến form trắc nghiệm (nếu có) hoặc chỉ hiển thị thông báo thành công và "Bạn có thể đóng tab này" chẳng hạn

**Comment by nghiatm341** [comment]
Lấy danh sách quiz có thêm bộ lọc theo class
