### ISSUE TITLE
Next-auth.js and MongoDB

### ISSUE THREAD

**Issue by nghiatm341** [MasterPi-2124/CNWeb30-Backend#15]
New approach: Session 
- https://authjs.dev/reference/adapter/mongodb
- https://chat.openai.com/share/25578bff-305b-4427-8798-ec7aa6c3ec06

**Comment by masterpi007** [comment]
no much time left, sed :'(

**Comment by nghiatm341** [comment]
Auth feature is hereby stalled indefinitely
