### ISSUE TITLE
Should we add update quizzes feature?

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#19]
like the title, if user want to update some information, they should be able to update the quiz. But should we add thiss? @nghiatm341

**Comment by nghiatm341** [comment]
Maybe it is allowed with conditions like the status must be incoming or maybe there's no record of that quiz

**Comment by nghiatm341** [comment]
> like the title, if user want to update some information, they should be able to update the quiz. But should we add thiss? @nghiatm341 

Maybe it is allowed with conditions like the status must be incoming or maybe there's no record of that quiz. Or maybe, if the conditions are not met, a new quiz with the exact details is created with some parts changed. Much to be discuss @MasterPi-2124

**Comment by nghiatm341** [comment]
Conclusion: Only delete, no update

**Comment by nghiatm341** [comment]
> Conclusion: Only delete, no update

Proof:
![image](https://github.com/MasterPi-2124/CNWeb30-Backend/assets/119276144/ecb8c9da-57a1-4dbd-9337-052a1f1b8a26)
