### ISSUE TITLE
Unused API

### ISSUE THREAD

**Issue by nghiatm341** [MasterPi-2124/CNWeb30-Backend#27]
Many API are redundant, using same method, etc.

**Comment by masterpi007** [comment]
1. QuizRecords
    - Unused API
    ![image](https://github.com/MasterPi-2124/CNWeb30-Backend/assets/49267398/cbd9f0df-f05a-4817-8015-f3ebe028ebc0)
    ![image](https://github.com/MasterPi-2124/CNWeb30-Backend/assets/49267398/d0159743-907b-4521-a2f5-bd944d2c50a7)
    - Modify:
        - Change `GET /quizRecords?quiz={quiz-id}` to `GET /quizRecords/{quiz-id}`, which returns a single quizRecords object of a quiz. No need to query all quiz records because we are only working with 1. 
        - Change `PUT /quizRecords/{id}` to normal `PUT /quizRecords/{quiz-id}`, with a custom path like in the `GET` method above.
2. Classes
    - Unused API
    ![image](https://github.com/MasterPi-2124/CNWeb30-Backend/assets/49267398/12cbc208-af4c-4e81-8440-5f15fd0bf593)
4. PUT Quiz and Class(?)
Don't remember if we mentioned it or not @nghiatm341

**Comment by nghiatm341** [comment]
@MasterPi-2124 
- [x] > 1. QuizRecords

>    
>    * Unused API
>      ![image](https://user-images.githubusercontent.com/49267398/246596812-cbd9f0df-f05a-4817-8015-f3ebe028ebc0.png)
>      ![image](https://user-images.githubusercontent.com/49267398/246596893-d0159743-907b-4521-a2f5-bd944d2c50a7.png)
>    * Modify:
>      
>      * Change `GET /quizRecords?quiz={quiz-id}` to `GET /quizRecords/{quiz-id}`, which returns a single quizRecords object of a quiz. No need to query all quiz records because we are only working with 1.
>      * Change `PUT /quizRecords/{id}` to normal `PUT /quizRecords/{quiz-id}`, with a custom path like in the `GET` method above.

Also create record api is also unused (the record creation is automatic with the quiz creation)

- [x] > 2. Classes

>    
>    * Unused API
>      ![image](https://user-images.githubusercontent.com/49267398/246597101-12cbc208-af4c-4e81-8440-5f15fd0bf593.png)

- [x] > 3. PUT Quiz and Class(?)

>    Don't remember if we mentioned it or not @nghiatm341
