### ISSUE TITLE
Class API

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#29]
- in Class object, it is great to have a param `quizzes` that shows a list of quiz IDs of that class
- When deleting a class, all quizzes of this class should be also removed too. 
@nghiatm341

**Comment by nghiatm341** [comment]
@MasterPi-2124 
- [x] > * in Class object, it is great to have a param `quizzes` that shows a list of quiz IDs of that class
- [x] > * When deleting a class, all quizzes of this class should be also removed too.

**Comment by nghiatm341** [comment]
What a coincidence, working on class too

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> * When deleting a class, all quizzes of this class should be also removed too.

Should records also be deleted as well?

**Comment by masterpi007** [comment]
yeah of course
