### ISSUE TITLE
quizRecoeds bug

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#31]
![image](https://github.com/MasterPi-2124/CNWeb30-Backend/assets/49267398/877759e2-a5f6-4350-a576-751c301cb21c)
Problem with PUT /quizRecords/{quiz_id}. also, createdAt is also not needed too

**Comment by nghiatm341** [comment]
@MasterPi-2124 
- [x] Quiz Record bug fix
- [x] Remove createAt

**Comment by nghiatm341** [comment]
Since createAt is almost like a primary key to the object in studentList, removing it causes mongo to automatically add _id property when the same record is added

**Comment by masterpi007** [comment]
so I have to add also `createdAt` param when sending the PUT request? In the payload example, the createdAt param is in the object

**Comment by masterpi007** [comment]
it's not finished yet, right? @nghiatm341 lmk when you merged that into main

**Comment by nghiatm341** [comment]
> so I have to add also `createdAt` param when sending the PUT request? In the payload example, the createdAt param is in the object
> 

@MasterPi-2124 
At first I want to add that so you can add the time manually. But if you find it unnecessary I'll remove it

**Comment by masterpi007** [comment]
current bugs:
- [ ] when PUT a new record, the response still returns the old data (not updated with that new record pushed). Not sure if it is serious or not because I did not use that.
- [x] a student can submit a lot of times (duplicate check)

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> * [ ]  when PUT a new record, the response still returns the old data (not updated with that new record pushed). Not sure if it is serious or not because I did not use that.

This is a default response of all api except get, they will return the old data before put, delete.
Would you like this to be removed or change? If change, do you mean change to return the updated version

> * [ ]  a student can submit a lot of times (duplicate check)

How would you like this to play out? Should I check ip address, student id, or both?

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> when PUT a new record, the response still returns the old data (not updated with that new record pushed). Not sure if it is serious or not because I did not use that.

This is the default with every update or delete. Do you wish to change it?
