### ISSUE TITLE
Next-auth

### ISSUE THREAD

**Issue by nghiatm341** [MasterPi-2124/CNWeb30-Backend#34]
Finally, users

**Comment by masterpi007** [comment]
yea please make it work: 
- example: https://next-auth-example.vercel.app/
- docs: https://nextjs.org/docs/pages/building-your-application/routing/authenticating
- backend adapters: https://authjs.dev/reference/adapters

**Comment by masterpi007** [comment]
How is it going sir? @nghiatm341

**Comment by nghiatm341** [comment]
> How is it going sir? @nghiatm341 

Still reading docs and examples. I'll try to get something running on a branch by tonight 
@MasterPi-2124

**Comment by nghiatm341** [comment]
@MasterPi-2124 
The more I research, the more I see that nextauth.js is for the front-end. The doc and many other examples online only show how to code the front-end with serverless authorization, since nextauth.js main focus is serverless. Basically, if you want the back-end to do the auth, you still have to handle jwt (provided by the back) and session with nextauth.

**Comment by masterpi007** [comment]
have you finished auth in be side yet? let me try if I can push some new data with new credentials ỏ not
@nghiatm341

**Comment by nghiatm341** [comment]
The branch responsible for this issue will need deeper refractors

- [x] Add auth to paths
- [x] Add ownerships to all data (add createdBy, updatedBy (may not needed) properties
- [ ] This depends on the second tasks: return class list with user (related to #38)

**Comment by nghiatm341** [comment]
@MasterPi-2124 
Why do user need classes property?

**Comment by masterpi007** [comment]
yeah I think it's redundant also. if we have `createdBy` properties in quizzes and classes, so we can easily get all quizzes or classes from an user ID

**Comment by masterpi007** [comment]
it;s done, thank you
