### ISSUE TITLE
Change live server to new DNS

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#37]
we have both FE and BE here, yay:
 - https://cn-web.artsakh.ventures
 - https://cn-web.artsakh.ventures/api
 - Swagger: https://cn-web.artsakh.ventures/api/swagger
 
@nghiatm341 please update in swagger config. All CORS enabled.

**Comment by nghiatm341** [comment]
@MasterPi-2124 

- [ ] Update swagger live server

**Comment by masterpi007** [comment]
We should remove all traces of server IP address from public API, because right now my Cloudflare setting does not support proxied yet

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> We should remove all traces of server IP address from public API, because right now my Cloudflare setting does not support proxied yet

So you want me to show only the dev server option, right?

**Comment by masterpi007** [comment]
no, still keep live server, but change IP to DNS URL. in the code if there are any URL with IP address, change it to DNS also.

Also, because I enabled CORS in DNS, the live server in swagger UI  must be that DNS to be able to work.

**Comment by nghiatm341** [comment]
After a quick check, the old URL with IP address only appears on swagger.
