### ISSUE TITLE
New Object: User (teacher)

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#38]
Properties:
- Name
- Classes
- Email
- Gender
- will add more....

**Comment by nghiatm341** [comment]
The classes will be added later

**Comment by masterpi007** [comment]
no need to add classes, and userName is also redundant too. Right now I am using email and password
Also, need to add email validate: `Msd@gmail.com` and `msd@gmail.com` are counted as 2 different emails right now, which should not be
