### ISSUE TITLE
remove users capability?

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#49]
yeah I fucked up with users lol. Also maybe allow them to change info?

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> yeah I fucked up with users lol. 

What did you mean by "f*cked up"

> Also maybe allow them to change info?

User can change basic infos except email and password, right?

Email is like an id so we can't change that easily, probably
Password would require a specialize form on the front, like new password, reconfirm new password, old password
But then again, to change basic info we might also need the old password so you could put everything in a form, just recycle the register form, add a field to put in the old password to confirm.
What do you think?

**Comment by masterpi007** [comment]
ahh just created too many accounts and did not remember any passwords lol. yeah maybe just change the name, right? the only param left we can change

**Comment by masterpi007** [comment]
I am making an account page so the users can see their personal info. so probably need an authorized  GET method of a user

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> ahh just created too many accounts and did not remember any passwords lol. yeah maybe just change the name, right? the only param left we can change

For now, user only have name and gender as basic info (I consider email and password as login info). 

> I am making an account page so the users can see their personal info. so probably need an authorized GET method of a user

Sure, I can add that. How do you want to inplement it?
Suggestion: I could add an api without any id in params for this. It does not need any input from front, except the jwt token (because you need to be logged in), the back will just check that token, decode the token, get the user id and return the info of that user
What do you think?

**Comment by masterpi007** [comment]
I think just GET /users/{userID} maybe? but to do that, userID has to be in jwt token, and I will extract the quizID from that and get the info later on. so jwt may need contain only userID for saving storage?

**Comment by masterpi007** [comment]
also, I made a signout button that just removes jwt token in browser. If I log in again with the same credential, will it be fail or overwrite the old jwt in backend? if its failed, should ww also need PUT /signout ?

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> I think just GET /users/{userID} maybe? but to do that, userID has to be in jwt token, and I will extract the quizID from that and get the info later on. so jwt may need contain only userID for saving storage?

Your choice, the teacher needs to login (having the token) before GET the user info. With just token, back can get the userId and subsequently, the user info (The token already have the userId, that how I can check with createBy from before)

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> also, I made a signout button that just removes jwt token in browser. If I log in again with the same credential, will it be fail or overwrite the old jwt in backend? if its failed, should ww also need PUT /signout ?

The back does not actually store the jwt tokens. It just verify the token it received
The token also store its own start time and end time. So every login will have a (maybe just slightly) different token
Unless I misunderstand "same credential" means.

**Comment by masterpi007** [comment]
coool, so it will count these same credentials as 2 different login sessions
