### ISSUE TITLE
Class Dashboard

### ISSUE THREAD

**Issue by Nelly502** [MasterPi-2124/CNWeb30-Backend#52]
-Sau khi xóa class, thì hệ thống vẫn lưu lại class đó, chỉ xóa thông tin -> cần F5 lại thì class trống đó mới được hệ thống xóa.
- Note: bug này không tồn tại lúc xóa quiz

**Comment by nghiatm341** [comment]
@Nelly502 
Việc lưu lại này em thây thấy ở swagger hay ở front? 
Theo mô tả của em thì lỗi này giống lỗi front nhiều hơn. 
Em có thể nói rõ hơn được không?
Nếu đây là lỗi front thì em cần phải tạo issue cho repo của front nhé

@MasterPi-2124 
Do you have any info about this bug?

**Comment by masterpi007** [comment]
yeah havent got that before. But with latest commit, I think the problem was solved. Need checks from @Nelly502 and close it later

**Comment by masterpi007** [comment]
it was solved in the latest commit
