### ISSUE TITLE
quizRecord failed cases

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#53]
~## 1. Students submitted more than once
Check student ID and IP address. First, check the IP to prevent further access. then still allow students to submit and return failure if the ID is in the list. That failed record should still be in the records list~ ***handled from front***

 - [x] In GET `/quizRecords/{quizId}`, it could be great if we have `IPList` array containing all IP addresses that have submitted the quiz
 - [x] Check student ID and return if the ID is in the records
 - [x] In the `note` param, change the value to `FAIL_EXISTED` instead of the default uninformative `a note`
## 2. The student location is too far
When the quiz asks for a student's location, it will calculate the distance to the teacher's location and return if it is far or not. In the far case, it will prevent the student from going further, but it also should save the IP address in the records to prevent future submissions from the same device.
- [ ] A record can also contain empty `studentId` and `studentName`, but IP is the failed IP
- [ ] `note` param now is `FAIL_DISTANCE`
## 3. Incorrect teacher's location
Some users will find a way to change the teacher's location by changing `lat` and `lon` in the URL path to their coordination and thus their submission will be valid.
- [ ] Because we can't add that location in the process of creating the quiz (possible but I don't like that), we will need to convert path `{quizID}?lat=12.12312&lon=32.4343` to some encoded strings so that students can not decode and change `lat` and `lon`
- [ ] some other ways in backend?
## 4. Expired quiz
Only apply to the case when a student is working on the quiz and press Submit button after the quiz is expired. The response should return an error and still save the record with `note` is `FAIL_EXPIRED`
- [ ] Save record with `note`: `FAIL_EXPIRED`
## 5. Submission amount > total students
Rarely but also need to check that. How should we handle this?

**Comment by masterpi007** [comment]
3., actually I don't think encoding is a good idea. for example, if we use base64, people still can decode it lol

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> 1. Students submitted more than once

> In GET /quizRecords/{quizId}, it could be great if we have IPList array containing all IP addresses that have submitted the quiz

The IP addresses already shows within the studentList in quizRecord. Did you mean you want to compile all of those IP addresses to put them in a IPList array so you can check them easier?

> Check student ID and return if the ID is in the records

What do you need with this request? Do you want an API to check? Do you need the studentId in quizRecord (already there)? Do you want a studentId list array like I said above

> In the note param, change the value to FAIL_EXISTED instead of the default uninformative a note
OK

**Comment by masterpi007** [comment]
first one: Yes thats what I meaned, just like a studentList, IPList will make it easier to check if IP is in the list or not

With GET quizRecords/quizID, I think we can both check IP and studentID in that, same method. So an additional IPList is not necessary anymore if I still need to query studentID in studentList

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> 2. The student location is too far

> A record can also contain empty studentId and studentName, but IP is the failed IP
> note param now is FAIL_DISTANCE

What do you mean failed IP? Do you mean that in the case of wrong location, that front will send a record that have empty studentId, empty studentName, the failed IP? The location is not stored so I do not think the back can check location to fix the note. 
How can I tell if the input is FAIL_DISTANCE? Is it that if studentId and studentName both empty the back will consider that FAIL_DISTANCE?

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> first one: Yes thats what I meaned, just like a studentList, IPList will make it easier to check if IP is in the list or not
> 
> With GET quizRecords/quizID, I think we can both check IP and studentID in that, same method. So an additional IPList is not necessary anymore if I still need to query studentID in studentList

I mean, it may not be necessary, but it can help the front with data handling. I can add both IPList and studentIdList if it helps

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> 3. Incorrect teacher's location

> Because we can't add that location in the process of creating the quiz (possible but I don't like that), we will need to convert path {quizID}?lat=12.12312&lon=32.4343 to some encoded strings so that students can not decode and change lat and lon

Can you put that location info in the body instead of the params? It will make the cheating harder
Or you do not like that?

> some other ways in backend?

Hmm, not so sure. Maybe the back can receive the location from the student from PUT quizRecord, but because teacher location is not stored (and the front handle the location from that start) so it might be really hard to compare. The back might need an out-of-the-box solution

**Comment by masterpi007** [comment]
> @MasterPi-2124
> 
> > first one: Yes thats what I meaned, just like a studentList, IPList will make it easier to check if IP is in the list or not
> > With GET quizRecords/quizID, I think we can both check IP and studentID in that, same method. So an additional IPList is not necessary anymore if I still need to query studentID in studentList
> 
> I mean, it may not be necessary, but it can help the front with data handling. I can add both IPList and studentIdList if it helps

maybe just let me handle with studentList for simply

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> 4. Expired quiz
Only apply to the case when a student is working on the quiz and press Submit button after the quiz is expired. The response should return an error and still save the record with note is FAIL_EXPIRED

Sure, I can check this

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> 5. Submission amount > total students
Rarely but also need to check that. How should we handle this?

I could pull the number of student from class (from quiz), count the number of submission the put them as 2 properties in quizRecord when you GET it
What do you think?

**Comment by masterpi007** [comment]
> @MasterPi-2124
> 
> > 3. Incorrect teacher's location
> 
> > Because we can't add that location in the process of creating the quiz (possible but I don't like that), we will need to convert path {quizID}?lat=12.12312&lon=32.4343 to some encoded strings so that students can not decode and change lat and lon
> 
> Can you put that location info in the body instead of the params? It will make the cheating harder Or you do not like that?

I have thought about that at first. but we only provide students the URL, so we can only encode it, or store it in backend side. right now I am doing multiple encodes so maybe it's harder lmao.

> > some other ways in backend?
> 
> Hmm, not so sure. Maybe the back can receive the location from the student from PUT quizRecord, but because teacher location is not stored (and the front handle the location from that start) so it might be really hard to compare. The back might need an out-of-the-box solution

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> I have thought about that at first. but we only provide students the URL, so we can only encode it, or store it in backend side. right now I am doing multiple encodes so maybe it's harder lmao.

How about this? 
The location will be stored inside the quiz. The location will be updated when the quiz is created and when the user click on show link/QR. I'll change the model to store location and add an API to change location. Front just need to call this API both those time I mentioned. 
quizRecord will also stored student location. That way I can handle the location comparison.

**Comment by masterpi007** [comment]
> @MasterPi-2124
> 
> > 2. The student location is too far
> 
> > A record can also contain empty studentId and studentName, but IP is the failed IP
> > note param now is FAIL_DISTANCE
> 
> What do you mean failed IP? Do you mean that in the case of wrong location, that front will send a record that have empty studentId, empty studentName, the failed IP? The location is not stored so I do not think the back can check location to fix the note. How can I tell if the input is FAIL_DISTANCE? Is it that if studentId and studentName both empty the back will consider that FAIL_DISTANCE?

oh sorry did not notice that. I think this case with empty student ID and name is the only case, so you can detect when empty info -> return FAILED_DISTANCE

**Comment by masterpi007** [comment]
> @MasterPi-2124
> 
> > I have thought about that at first. but we only provide students the URL, so we can only encode it, or store it in backend side. right now I am doing multiple encodes so maybe it's harder lmao.
> 
> How about this? The location will be stored inside the quiz. The location will be updated when the quiz is created and when the user click on show link/QR. I'll change the model to store location and add an API to change location. Front just need to call this API both those time I mentioned. quizRecord will also stored student location. That way I can handle the location comparison.

It will lead to the other problem. What if teacher creates quiz when he is home? so maybe encoding is the only way to this

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> It will lead to the other problem. What if teacher creates quiz when he is home? so maybe encoding is the only way to this

That's why I also want to update the theoretically stored location when the teacher click on show link/QR code

**Comment by masterpi007** [comment]
> @MasterPi-2124
> 
> > It will lead to the other problem. What if teacher creates quiz when he is home? so maybe encoding is the only way to this
> 
> That's why I also want to update the theoretically stored location when the teacher click on show link/QR code

ahh it makes sense now. But I already working on encoding stuff so I will get back to you later with that. right now I encoded 4 times lol

**Comment by nghiatm341** [comment]
@MasterPi-2124 
So the back will stored quizRecord no matter what, it just assign the isValid and note depend on what data it received. Right?

**Comment by masterpi007** [comment]
right now yes. hope we dont have other failed cases

**Comment by nghiatm341** [comment]
@MasterPi-2124 
I will now tally the tasks for this issue. Correct me if i'm wrong

- Store and validate quizRecord no matter what: 
- [ ] If IP and/or studentId existed => note = FAIL_EXISTED
- [ ] If both studentId and studentName are empty => note = FAIL_DISTANCE
- [ ] If passed the endTime => note = FAIL_EXPIRED

- submission count
- [ ] GET quizRecord will now return number of submission from records and student count from class (names pending)

**Comment by masterpi007** [comment]
LGTM!

**Comment by masterpi007** [comment]
> @MasterPi-2124
> 
> > I have thought about that at first. but we only provide students the URL, so we can only encode it, or store it in backend side. right now I am doing multiple encodes so maybe it's harder lmao.
> 
> How about this? The location will be stored inside the quiz. The location will be updated when the quiz is created and when the user click on show link/QR. I'll change the model to store location and add an API to change location. Front just need to call this API both those time I mentioned. quizRecord will also stored student location. That way I can handle the location comparison.

look like I have to store teacher's location in the backend side. there is no way to ensure that teacher's location is still valid with no checking.

Actually we can also have a `fancy` solution: 
 
When the teacher opens the modal, it will collect the location and combine it with quizID into a string, and then calculate the SHA256 hash of that generated string. the hash will be included in the quiz object in the server side. When a student change location in the query param, it will generate a different string with a different SHA256 hash, which is of course, invalid.

Is that complicated and how do u think? @nghiatm341

**Comment by masterpi007** [comment]
just found out that `note` and `isValid` params are in body of PUT /quizRecord @nghiatm341

**Comment by masterpi007** [comment]
@nghiatm341 I think 1. can be solved all from front end side. Please ignore it and working on others

**Comment by nghiatm341** [comment]
@MasterPi-2124 
The fancy solution you mention before, I could easily add a property to store that SHA256 string in either quiz or record.
Which one would you prefer?

**Comment by nghiatm341** [comment]
@MasterPi-2124 
Also, in the event that a student input violate multiple faults. Should I add all of the notes in the note like "FAIL_EXISTED FAIL_DISTANCE FAIL_EXPIRED" or how many does not matter, as long as there is a violation, just choose one and that's enough?

**Comment by masterpi007** [comment]
I think it would be too much work to do to add sha hash in a quiz or the record. Right now Im also using AES encryption to validate the string, but it's for the short term only. But for demo purpose, I think we can temporarily pause it and focus on other things too @nghiatm341

**Comment by nghiatm341** [comment]
@MasterPi-2124 
> Also, in the event that a student input violate multiple faults. Should I add all of the notes in the note like "FAIL_EXISTED FAIL_DISTANCE FAIL_EXPIRED" or how many does not matter, as long as there is a violation, just choose one and that's enough?

**Comment by masterpi007** [comment]
I think just update it with the latest value then
