### ISSUE TITLE
sort quizzes in class object by startDate

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/CNWeb30-Backend#57]

**Comment by masterpi007** [comment]
hah issues getting easier now lol :))

**Comment by nghiatm341** [comment]
@MasterPi-2124 
Do you want this as an option (like adding something like "?sortBy=..." to the api path)?
Or do you wnat this sort by default no matter what?

**Comment by masterpi007** [comment]
I think just leave it as default

**Comment by nghiatm341** [comment]
@MasterPi-2124 
Forgot to ask, sort by startTime, do you want latest startTime first?
